---
- name: get mearki devices
  connection: local
  hosts: localhost
  vars_files:
    - "secrets/vault.yml"
  vars:
    org_id: "{{ org }}"

  tasks:
   - name: get the list of devices for organization {{ org_id }}
     meraki_device:
       auth_key: "{{ auth_key }}"
       org_id: "{{ org_id }}"
       state: query
     delegate_to: localhost
     register: deviceinformation

   - debug: var=deviceinformation
